annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 0.6.3
dependencies:
  - name: common
    version: 24.1.2
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A self-hosted dashboard that puts all your feeds in one place
home: https://truecharts.org/charts/incubator/glance
icon: https://truecharts.org/img/hotlink-ok/chart-icons/glance.webp
keywords:
  - glance
  - dashboard
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: glance
sources:
  - https://github.com/glanceapp/glance
  - https://github.com/truecharts/charts/tree/master/charts/incubator/glance
type: application
version: 0.0.1
